### ISSUE TITLE
Different hash algorithms within the same RR

### ISSUE THREAD

**Issue by timwattenberg** [pusateri/draft-pusateri-dnsop-update-timeout#1]
I'm not sure if I see a case where multiple/different hash algorithms would be used within the same TIMEOUT RR.

@pusateri Do you had a specific use case in mind?

**Comment by pusateri** [comment]
Since the TIMEOUT RR is actually a collection of state from different sources over different time periods, there is a potential for default algorithm changes to occur on a single server or due to unavailability of an UPDATE server for a period of time to merge records between failover servers with different default algorithms.

This is not going to be a common scenario but one that could occur and therefore, I accounted for.

**Comment by timwattenberg** [comment]
Ah, I see – this scenario is totally valid. I think it would be good to add this comment (quite literally) as an explanation to the draft...

**Comment by pusateri** [comment]
ok, I can add this.
