### ISSUE TITLE
Make TIMEOUT queryable

### ISSUE THREAD

**Issue by timwattenberg** [pusateri/draft-pusateri-dnsop-update-timeout#11]

**Comment by pusateri** [comment]
Comments from Joe Abley:

New RRTypes are supposed to be handled by old software that pre-dates them because they can be treated as opaque types. That's not the case if new RRTypes are encumbered with requirements for special handling at query or signing time (as described in your section 2).

This seems like a significant architectural change that in effect updates 1034 and 1035 as well as 3597. This would be a much more straightforward and uncontroversial proposal if it was simply a specification for use of a new RRType that made no changes at all to the rest of the protocol.

**Comment by pusateri** [comment]
This really comes down to "Should TIMEOUT RRs act like any other RR?" I think the answer is yes!
