### ISSUE TITLE
Should we sort TIMEOUT blocks (instances)?

### ISSUE THREAD

**Issue by pusateri** [pusateri/draft-pusateri-dnsop-update-timeout#18]
Mark Andrews comments:

Sorting of timeout blocks is so that you can look at the first timeout when working out
which TIMEOUT needs to be processed first in a zone.

**Comment by pusateri** [comment]
It's not clear to me if this is just an implementation issue and has little consequence on the TIMEOUT RR as saved in the database.

**Comment by timwattenberg** [comment]
I see where Mark is coming from:
If all instances in one RR are sorted by expiry time and the expiry time of the first instance is not met, the name server can and SHOULD stop processing (mainly calculating the hashes) of this TIMEOUT RR. (SHOULD-case in my eyes, because other from being a little less efficient in processing the result is the same)

We could even extend this to a point where we recommend calculating the hashes only after the expiry time of the instance has come (there‘s really no point of doing so before).

**Comment by pusateri** [comment]
organizing the RRs in your implementations timer queue and storing them in the RDATA section are two very different things. Why does it matter the order in the RDATA section? All of the nice things about ordering Mark suggests happen in memory in the implementation after reading the RDATA.

**Comment by timwattenberg** [comment]
I agree that this is heavily implementation-dependent. I‘m ok with leaving this untouched and wait if this comes up in further discussions.

**Comment by pusateri** [comment]
Closing for now. It can be re-opened if needed.
