### ISSUE TITLE
Primary/Secondary vs. Master/Slave

### ISSUE THREAD

**Issue by pusateri** [pusateri/draft-pusateri-dnsop-update-timeout#7]
The current document mixes this terminology. Not sure which is better to use. DNS Update uses Master/Slave. Need to determine if there is a difference.

**Comment by timwattenberg** [comment]
If memory serves me right, there was an effort to move away from the terms Master/Slave towards Primary/Secondary, due to the negative historical aftertaste of the word stem. The DNS Update-RFC is probably "too old" and was passed prior to this discussion...

I would suggest using Primary/Secondary.
